version: '3'

services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    privileged: true
    ports:
      - "8080:80"
    volumes:
      - .:/app/
      - /dev:/dev
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    privileged: true
    volumes:
      - .:/app/
      - /dev/:/dev/
